### ISSUE TITLE
Generate reports from XCTest results

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#110]
- Enables users to visualize results as offline reports.
- Integrate test results with other system/tools using standard reporting format
- OCUnit reports (out-of-the-box results format for XCTest)

### Expected Behaviors
Useful reports are:
- HTML reports
- JUnit XML reports

### Test Case
- [x] No test case generates valid empty reports
- [x] All executed tests appear in the reports
- [x] Test failures match in the reports
- [x] New reports overwrite the old reports
- [x] Test reports exist after test execution
