### ISSUE TITLE
Support XCTest on Linux

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#114]
XCTest is the most popular testing framework for Swift. Given Swift is supported on both macOS and Linux, it's natural to support both operating systems.

### Expected Behaviors
Building on the XCTest support for macOS, support for Linux provide its own challenge. The implementation use [swift-corelibs-xctest](https://github.com/apple/swift-corelibs-xctest). Its package as a standalone executable as opposed to a bundle. At runtime, it doesn't require the `xctest` driver application.

#### Out of scope
- `swift-corelibs-xctest` requires the developer to declare each test case/test suite. Gradle can generate the `LinuxMain.swift` file (autodetection).
- Parallel execution of the tests
- Report generation
- macOS support for `swift-corelibs-xctest`

### Test Cases
- [ ] Behave well when no tests are defined
- [ ] Honor added, removed, and renamed tests
- [x] Execute tests from Gradle
