### ISSUE TITLE
Improve performance of XCTest execution from CLI

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#115]
By minimizing the test execution time, Gradle improves the feedback loop to the developers waiting for his build to complete.

### Expected Behaviors
This epic covers:
- Test filters using `--test` flag
- Parallel test execution

### Test Cases
- [ ] Honor filters passed to `--test` flags
- [ ] Honor wildcard in filters passed to `--test` flags
- [ ] No `--test` filters executes all tests
- [ ] Test are executed in parallel

**Comment by lacasseio** [comment]
Parallel execution on macOS with Xcode's implementation of XCTest can be achieved through Objective-C runtime reflection. See [Swift PM helper](https://github.com/apple/swift-package-manager/blob/master/Sources/swiftpm-xctest-helper/main.swift) for more information.

**Comment by lacasseio** [comment]
Following [this discussion on Slack](https://gradle.slack.com/archives/C5DTC5KGC/p1502765437000121), XCTest should be discoverable by Gradle that works for both macOS and Linux. Some possible options are:
1. no discovery, developer maintains a list of test cases and we use that list on _all_ platforms
2. discovery using a bundle on macOS, no discovery on other platforms so developer maintains a list of test cases
3. use a naming scheme and run any test class whose source file matches that naming scheme
4. scan the source files to discover test classes
5. scan the object files  to discover test classes

It would be good to end up with a cross-platform discovery strategy (and one we can reuse for other test frameworks).
