### ISSUE TITLE
Link avoidance for C++ and Swift plugins

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#117]
By minimizing the link time, Gradle improves the feedback loop to the developers waiting for his build to complete.

### Expected Behavior
No linking on the consumer side of a shared library should occur if the code change only affects the implementation (not the exported function prototype). The linking of a shared library should only be used for building the import table.

### Test Cases
- [ ] Relink with the library that had ABI changes to an existing imported function
- [ ] Doesn't relink with the library if an exported function was only added 
- [ ] Doesn't relink with the library if only the implementation of a function changes
- [ ] Doesn't relink with the library if a new function was added/removed/reexported which change the ordinal number of functions imported by name
- [ ] Relink with the library if a new function was added/removed/reexported which change the ordinal number of functions imported by ordinal number
- [ ] Doesn't relink with the library if an exported function is removed, wasn't previously used and doesn't change the ordinal number of the other exported functions
- [ ] Doesn't relink with the library if an exported function had ABI change but isn't imported by the consumer
