### ISSUE TITLE
Support for XCTest framework in Swift on macOS

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#78]
XCTest framework is widely used for Swift and Objective-C testing. Gradle will support basic functionality for usage in both CLI and XCode. We are looking to be able to achieve the following with this work:
- [x] Build a single XCTest bundle
- [x] The XCTest bundle can be run from Gradle
- [ ] ~Test results generate an HTML report to be consumed locally~ (https://github.com/gradle/gradle-native/issues/110)
- [ ] ~Test results are included inside build scans~ (https://github.com/gradle/gradle-native/issues/109)
- [ ] ~Xcode integration allows users to build and execute XCTest bundle from within the IDE~ (https://github.com/gradle/gradle-native/issues/108)
- [x] Update samples

### Test coverage
- [x] Add test coverage for `xctest` extension
- [x] No source change doesn't recompile/relink/retest tasks

All configuration/customization is out of scope for this epic.

**Comment by adammurdoch** [comment]
It would be good to clarify what "basic" support means. There are lots of capabilities we _could_ offer in this first round, but we want to do just enough to get some feedback and to discover what it actually means to offer test support for Swift.

**Comment by lacasseio** [comment]
Good point @adammurdoch, I modified the description to clarify what "basic" support means.

**Comment by adammurdoch** [comment]
I'd move some of the scope out of this epic. The idea of these initial "basic" epics to get a feel for what the feature should do, but we don't need to and shouldn't implement the complete feature at this point. I'd limit the scope to something like:

- I can run _all_ tests for a module from the command-line
- I can build and run _all_ tests for a module from Xcode.

I'd leave out reporting (beyond some text on the console), build scan integration (beyond what we get for free), and running an individual test case or class from Xcode, and move these features to a later 'support the development lifecycle from Xcode' epic. We may or may not implement some of those things immediately after completing this basic epic, but I think we should focus on getting _something_ implemented and in master.

**Comment by lacasseio** [comment]
Sounds about right. I will split this as suggested.

**Comment by lacasseio** [comment]
Xcode integration was split out in https://github.com/gradle/gradle-native/issues/108.

**Comment by lacasseio** [comment]
XCTest integration with build scan was split out in https://github.com/gradle/gradle-native/issues/109.

**Comment by lacasseio** [comment]
Report generation was split out in https://github.com/gradle/gradle-native/issues/110.

**Comment by adammurdoch** [comment]
Make sure the samples are updated to show this feature in action.

**Comment by adammurdoch** [comment]
I don't really consider XCTest support delivered while the `XCTest` task extends from the JVM's `Test` task and so drags in all kinds of settings that don't make sense. I think it's ok to do this as a separate story, but would be better as part of this story.

**Comment by lacasseio** [comment]
Good point @adammurdoch. I reopened the issue and attached the right issue to this epic. I will try to get this going this week.

**Comment by lacasseio** [comment]
The `XCTest` task extending from the JVM `Test` task will be addressed as the [cross-cutting roadmap item for `XCTest` in general (both macOS and Linux)](https://github.com/gradle/gradle-native/issues/200). This epic is focusing only on `XCTest` for macOS.

**Comment by lacasseio** [comment]
Everything for XCTest on macOS is working as expected.
