### ISSUE TITLE
Issues from gradle/gradle

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle-native#83]
I discovered this new repository dedicated to the native side of Gradle. Below 3 links to the issues I posted
- [x] [native: changing the parentDir of a sharedLibraryLinkFile is not honored if different from the parentDir of the sharedLibraryFile](https://github.com/gradle/gradle/issues/2649)
- [x] [native: add a Locale dimension replacing the Flavor used to specify the locale](https://github.com/gradle/gradle/issues/2637)
- [x] [native: add SharedLibraryBinary properties for the Export file & the Program Debugging file](https://github.com/gradle/gradle/issues/2636)

**Comment by lacasseio** [comment]
Thanks @zosrothko for the reminder, the native team taking care of this board also subscribes to the [`gradle/gradle`](https://github.com/gradle/gradle) board. In the future, you don't need to aggregate the issue here.
